import { createSyncStoragePersister } from '@tanstack/query-sync-storage-persister'
import { TanStackDevtools } from '@tanstack/react-devtools'
import { QueryClient } from '@tanstack/react-query'
import { PersistQueryClientProvider } from '@tanstack/react-query-persist-client'
import {
  createRootRoute,
  HeadContent,
  Link,
  Scripts,
} from '@tanstack/react-router'
import { TanStackRouterDevtoolsPanel } from '@tanstack/react-router-devtools'
import { useEffect } from 'react'
import { AppSidebar } from '../components/AppSidebar'
import { AuthGate } from '../components/AuthGate'
import { CommandPalette } from '../components/CommandPalette'
import { FeedbackProvider } from '../components/Feedback'
import { Header } from '../components/Header'
import { TooltipProvider } from '../components/ui/tooltip'
import { queryKeys, STATUS_CACHE_MAX_AGE } from '../hooks/queries'
import { AppShellProvider } from '../hooks/useAppShell'
import { JobProvider } from '../hooks/useJob'
import { SelectedConfigProvider } from '../hooks/useSelectedConfig'
import { THEME_INIT_SCRIPT } from '../lib/theme'
import * as m from '../paraglide/messages'
import { getLocale } from '../paraglide/runtime'

import appCss from '../styles.css?url'

// Create a QueryClient instance
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 10, // 10 seconds
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
})

// No storage during SSR or when the browser blocks it, the cache then just is not persisted
const browserStorage = (() => {
  try {
    return typeof window === 'undefined' ? undefined : window.localStorage
  } catch {
    return undefined
  }
})()

const persister = createSyncStoragePersister({
  storage: browserStorage,
  key: 'snapraid-ui-query-cache',
})

const persistOptions = {
  persister,
  maxAge: STATUS_CACHE_MAX_AGE,
  // Bump when the persisted data shape changes
  buster: '1',
  dehydrateOptions: {
    // Only the status is persisted; kept after a busy refetch too, which leaves its last data in place
    shouldDehydrateQuery: (query: {
      queryKey: readonly unknown[]
      state: { data: unknown }
    }) =>
      query.queryKey[0] === queryKeys.status[0] &&
      query.state.data !== undefined,
  },
}

export const Route = createRootRoute({
  notFoundComponent: () => (
    <div style={{ padding: '2rem', textAlign: 'center' }}>
      <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>
        {m.not_found_title()}
      </h1>
      <p style={{ fontSize: '1.25rem', marginBottom: '1.5rem' }}>
        {m.not_found_message()}
      </p>
      <Link to="/" style={{ color: '#0066cc', textDecoration: 'underline' }}>
        {m.not_found_go_home()}
      </Link>
    </div>
  ),
  head: () => ({
    meta: [
      {
        charSet: 'utf-8',
      },
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1',
      },
      {
        title: m.app_title(),
      },
      {
        name: 'theme-color',
        content: '#09090b',
      },
    ],
    links: [
      {
        rel: 'stylesheet',
        href: appCss,
      },
      { rel: 'icon', href: '/favicon.ico', sizes: '48x48' },
      {
        rel: 'icon',
        href: '/favicon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
      },
      { rel: 'apple-touch-icon', href: '/apple-touch-icon-180x180.png' },
      { rel: 'manifest', href: '/manifest.webmanifest' },
    ],
  }),

  shellComponent: RootDocument,
})

// The service worker is generated by vite-plugin-pwa during the build only
function useServiceWorker() {
  useEffect(() => {
    if (import.meta.env.PROD && 'serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => {})
    }
  }, [])
}

function RootDocument({ children }: { children: React.ReactNode }) {
  useServiceWorker()

  return (
    // The init script sets data-theme before React hydrates
    <html lang={getLocale()} suppressHydrationWarning>
      <head>
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: static script, sets the theme before the first paint */}
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        <HeadContent />
      </head>
      <body>
        <PersistQueryClientProvider
          client={queryClient}
          persistOptions={persistOptions}
        >
          <AuthGate>
            <FeedbackProvider>
              <SelectedConfigProvider>
                <JobProvider>
                  <TooltipProvider>
                    <AppShellProvider>
                      <div className="flex min-h-svh">
                        <AppSidebar />
                        <div className="flex min-w-0 flex-1 flex-col">
                          <Header />
                          {children}
                        </div>
                      </div>
                      <CommandPalette />
                    </AppShellProvider>
                  </TooltipProvider>
                </JobProvider>
              </SelectedConfigProvider>
            </FeedbackProvider>
          </AuthGate>
          {import.meta.env.DEV && (
            <TanStackDevtools
              config={{
                position: 'bottom-right',
              }}
              plugins={[
                {
                  name: 'Tanstack Router',
                  render: <TanStackRouterDevtoolsPanel />,
                },
              ]}
            />
          )}
        </PersistQueryClientProvider>
        <Scripts />
      </body>
    </html>
  )
}
