#!/usr/bin/env bash
# Prepares a self-contained SnapRAID sandbox for local development:
#   - builds a pinned SnapRAID binary into dev/bin/
#   - creates fake data/parity disks under dev/sandbox/ with an initial sync
#   - leaves a few pending changes so diff/status have something to show
#
# Usage: dev/setup.sh [--reset]   (--reset recreates the sandbox from scratch)

set -euo pipefail

SNAPRAID_VERSION="${SNAPRAID_VERSION:-14.10}"

DEV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$DEV_DIR/bin"
CACHE_DIR="$DEV_DIR/.cache"
SANDBOX="$DEV_DIR/sandbox"
# The disks: in the sandbox by default; DISKS_DIR=/mnt puts them where a server has them
# (/mnt/disk1, /mnt/parity1), as the screenshots show them
DISKS="${DISKS_DIR:-$SANDBOX/disks}"
DISK_DIRS=(disk1 disk2 disk3 disk4 parity1)
# Each sandbox disk carries this file: only such a directory (or an empty one) is ever
# removed or filled, never a real disk that happens to be mounted at /mnt/disk1
MARKER=.snapraid-ui-sandbox
SNAPRAID="$BIN_DIR/snapraid"

# A disk directory the sandbox may use: missing, empty, or one of its own
sandbox_disk() {
  [[ ! -e "$1" ]] || [[ -f "$1/$MARKER" ]] || [[ -z "$(ls -A "$1")" ]]
}

for dir in "${DISK_DIRS[@]}"; do
  if ! sandbox_disk "$DISKS/$dir"; then
    echo "$DISKS/$dir is not a sandbox disk (no $MARKER in it), refusing to touch it" >&2
    exit 1
  fi
done

if [[ "${1:-}" == "--reset" ]]; then
  echo "Removing existing sandbox..."
  rm -rf "$SANDBOX"
  for dir in "${DISK_DIRS[@]}"; do rm -rf "${DISKS:?}/$dir"; done
fi

# --- SnapRAID binary -------------------------------------------------------

if [[ ! -x "$SNAPRAID" ]] || ! "$SNAPRAID" --version 2>/dev/null | grep -q "v$SNAPRAID_VERSION"; then
  echo "Building SnapRAID $SNAPRAID_VERSION..."
  for tool in curl tar gcc make; do
    command -v "$tool" >/dev/null || { echo "Missing required tool: $tool" >&2; exit 1; }
  done

  mkdir -p "$CACHE_DIR" "$BIN_DIR"
  tarball="$CACHE_DIR/snapraid-$SNAPRAID_VERSION.tar.gz"
  src="$CACHE_DIR/snapraid-$SNAPRAID_VERSION"

  [[ -f "$tarball" ]] || curl -fsSL -o "$tarball" \
    "https://github.com/amadvance/snapraid/releases/download/v$SNAPRAID_VERSION/snapraid-$SNAPRAID_VERSION.tar.gz"
  rm -rf "$src"
  tar -xzf "$tarball" -C "$CACHE_DIR"
  (cd "$src" && ./configure >/dev/null && make -j"$(nproc)" >/dev/null)
  cp "$src/snapraid" "$SNAPRAID"
fi
echo "Using $("$SNAPRAID" --version | head -1)"

# --- Deno (only if not installed) -------------------------------------------

DENO_VERSION="${DENO_VERSION:-2.9.7}"
TOOLS_DIR="$DEV_DIR/tools"

if ! command -v deno >/dev/null && [[ ! -x "$TOOLS_DIR/deno" ]]; then
  echo "Deno not found, downloading Deno $DENO_VERSION..."
  command -v unzip >/dev/null || { echo "Missing required tool: unzip" >&2; exit 1; }
  mkdir -p "$CACHE_DIR" "$TOOLS_DIR"
  zip="$CACHE_DIR/deno-$DENO_VERSION.zip"
  curl -fsSL -o "$zip" \
    "https://github.com/denoland/deno/releases/download/v$DENO_VERSION/deno-$(uname -m)-unknown-linux-gnu.zip"
  unzip -oq "$zip" -d "$TOOLS_DIR"
fi

# --- Sandbox ---------------------------------------------------------------

if [[ -f "$SANDBOX/snapraid.conf" ]]; then
  echo "Sandbox already exists at $SANDBOX (use --reset to recreate)"
  exit 0
fi

echo "Creating sandbox at $SANDBOX..."
mkdir -p "$SANDBOX"/logs
for dir in "${DISK_DIRS[@]}"; do
  mkdir -p "$DISKS/$dir"
  echo "Disk of the SnapRAID UI demo sandbox (dev/setup.sh), removed by dev/setup.sh --reset" > "$DISKS/$dir/$MARKER"
done

# Random file of given size in KiB
mkfile() {
  mkdir -p "$(dirname "$1")"
  head -c "$(($2 * 1024))" /dev/urandom > "$1"
}

mkfile "$DISKS/disk1/photos/2024/holiday-001.jpg" 900
mkfile "$DISKS/disk1/photos/2024/holiday-002.jpg" 1100
mkfile "$DISKS/disk1/photos/2025/birthday.jpg" 750
mkfile "$DISKS/disk1/documents/taxes-2024.pdf" 300
mkfile "$DISKS/disk1/documents/contract.pdf" 120
mkfile "$DISKS/disk2/movies/big-buck-bunny.mkv" 4096
mkfile "$DISKS/disk2/movies/sintel.mkv" 3072
mkfile "$DISKS/disk2/music/album/01-intro.flac" 600
mkfile "$DISKS/disk2/music/album/02-theme.flac" 800
mkfile "$DISKS/disk3/backups/laptop-2025-01.tar" 2048
mkfile "$DISKS/disk3/backups/laptop-2025-06.tar" 2560
mkfile "$DISKS/disk3/projects/notes.txt" 4
mkfile "$DISKS/disk3/tmp/cache.bin" 64
mkfile "$DISKS/disk4/series/season-1/episode-01.mkv" 1536
mkfile "$DISKS/disk4/series/season-1/episode-02.mkv" 1536
# Copies of the same files, for the duplicates page
dupfile() {
  mkdir -p "$(dirname "$2")"
  cp "$1" "$2"
}
dupfile "$DISKS/disk1/photos/2024/holiday-001.jpg" "$DISKS/disk3/backups/phone/holiday-001.jpg"
dupfile "$DISKS/disk1/photos/2024/holiday-002.jpg" "$DISKS/disk3/backups/phone/holiday-002.jpg"
dupfile "$DISKS/disk2/movies/sintel.mkv" "$DISKS/disk4/downloads/sintel.mkv"
dupfile "$DISKS/disk2/movies/sintel.mkv" "$DISKS/disk3/backups/old-pc/sintel (1).mkv"

cat > "$SANDBOX/snapraid.conf" <<EOF
# Generated by dev/setup.sh - development sandbox, safe to modify or delete

parity $DISKS/parity1/snapraid.parity

content $DISKS/parity1/snapraid.content
content $DISKS/disk1/snapraid.content
content $DISKS/disk2/snapraid.content

data disk1 $DISKS/disk1/
data disk2 $DISKS/disk2/
data disk3 $DISKS/disk3/
data disk4 $DISKS/disk4/

exclude *.content
exclude /.snapraid-ui-sandbox
exclude /tmp/
exclude /lost+found/

blocksize 64
autosave 10
EOF

cat > "$SANDBOX/config.json" <<'EOF'
{
  "version": "1.0.0",
  "snapraidConfigs": [
    {
      "name": "Media Array",
      "path": "snapraid.conf",
      "enabled": true
    }
  ],
  "logs": {
    "maxHistoryEntries": 50,
    "directory": "logs",
    "maxFiles": 100,
    "maxAge": 30
  }
}
EOF

# Real jobs with their logs, in order; dev/seed-demo.ts moves them back in time
run=0
snapraid_logged() {
  run=$((run + 1))
  "$SNAPRAID" --test-skip-device -c "$SANDBOX/snapraid.conf" -l "$SANDBOX/logs/run-$run-$1.log" "$@" >/dev/null 2>&1
}

echo "Running sync, scrub and touch..."
snapraid_logged sync || { echo "Initial sync failed" >&2; exit 1; }
snapraid_logged scrub -p 100 -o 0
snapraid_logged touch
snapraid_logged sync

# Pending changes so diff/status/sync have something to do
mkfile "$DISKS/disk1/photos/2025/new-photo.jpg" 500
mkfile "$DISKS/disk2/music/album/02-theme.flac" 820
rm "$DISKS/disk3/backups/laptop-2025-01.tar"
mkfile "$DISKS/disk4/series/season-2/episode-01.mkv" 1700
mkdir -p "$DISKS/disk1/documents/archive"
mv "$DISKS/disk1/documents/contract.pdf" "$DISKS/disk1/documents/archive/contract.pdf"

# diff exits with 2 when there are differences
snapraid_logged diff || true
snapraid_logged status

# The jobs' history, disk usage, schedules and automation of a few weeks of use
DENO="$(command -v deno || echo "$TOOLS_DIR/deno")"
"$DENO" run --config "$DEV_DIR/../backend/deno.json" --allow-read --allow-write --allow-env \
  "$DEV_DIR/seed-demo.ts" "$SANDBOX"

echo
echo "Sandbox ready. Start the app with: ./start.sh --demo"
