#!/usr/bin/env bash
# Prepares a self-contained SnapRAID sandbox for local development:
#   - builds a pinned SnapRAID binary into dev/bin/
#   - creates fake data/parity disks under dev/sandbox/ with an initial sync
#   - leaves a few pending changes so diff/status have something to show
#
# Usage: dev/setup.sh [--reset]   (--reset recreates the sandbox from scratch)

set -euo pipefail

SNAPRAID_VERSION="${SNAPRAID_VERSION:-14.10}"

DEV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$DEV_DIR/bin"
CACHE_DIR="$DEV_DIR/.cache"
SANDBOX="$DEV_DIR/sandbox"
SNAPRAID="$BIN_DIR/snapraid"

if [[ "${1:-}" == "--reset" ]]; then
  echo "Removing existing sandbox..."
  rm -rf "$SANDBOX"
fi

# --- SnapRAID binary -------------------------------------------------------

if [[ ! -x "$SNAPRAID" ]] || ! "$SNAPRAID" --version 2>/dev/null | grep -q "v$SNAPRAID_VERSION"; then
  echo "Building SnapRAID $SNAPRAID_VERSION..."
  for tool in curl tar gcc make; do
    command -v "$tool" >/dev/null || { echo "Missing required tool: $tool" >&2; exit 1; }
  done

  mkdir -p "$CACHE_DIR" "$BIN_DIR"
  tarball="$CACHE_DIR/snapraid-$SNAPRAID_VERSION.tar.gz"
  src="$CACHE_DIR/snapraid-$SNAPRAID_VERSION"

  [[ -f "$tarball" ]] || curl -fsSL -o "$tarball" \
    "https://github.com/amadvance/snapraid/releases/download/v$SNAPRAID_VERSION/snapraid-$SNAPRAID_VERSION.tar.gz"
  rm -rf "$src"
  tar -xzf "$tarball" -C "$CACHE_DIR"
  (cd "$src" && ./configure >/dev/null && make -j"$(nproc)" >/dev/null)
  cp "$src/snapraid" "$SNAPRAID"
fi
echo "Using $("$SNAPRAID" --version | head -1)"

# --- Deno (only if not installed) -------------------------------------------

DENO_VERSION="${DENO_VERSION:-2.9.7}"
TOOLS_DIR="$DEV_DIR/tools"

if ! command -v deno >/dev/null && [[ ! -x "$TOOLS_DIR/deno" ]]; then
  echo "Deno not found, downloading Deno $DENO_VERSION..."
  command -v unzip >/dev/null || { echo "Missing required tool: unzip" >&2; exit 1; }
  mkdir -p "$CACHE_DIR" "$TOOLS_DIR"
  zip="$CACHE_DIR/deno-$DENO_VERSION.zip"
  curl -fsSL -o "$zip" \
    "https://github.com/denoland/deno/releases/download/v$DENO_VERSION/deno-$(uname -m)-unknown-linux-gnu.zip"
  unzip -oq "$zip" -d "$TOOLS_DIR"
fi

# --- Sandbox ---------------------------------------------------------------

if [[ -f "$SANDBOX/snapraid.conf" ]]; then
  echo "Sandbox already exists at $SANDBOX (use --reset to recreate)"
  exit 0
fi

echo "Creating sandbox at $SANDBOX..."
mkdir -p "$SANDBOX"/{disks/d1,disks/d2,disks/d3,parity,logs}

# Random file of given size in KiB
mkfile() {
  mkdir -p "$(dirname "$1")"
  head -c "$(($2 * 1024))" /dev/urandom > "$1"
}

mkfile "$SANDBOX/disks/d1/photos/2024/holiday-001.jpg" 900
mkfile "$SANDBOX/disks/d1/photos/2024/holiday-002.jpg" 1100
mkfile "$SANDBOX/disks/d1/photos/2025/birthday.jpg" 750
mkfile "$SANDBOX/disks/d1/documents/taxes-2024.pdf" 300
mkfile "$SANDBOX/disks/d1/documents/contract.pdf" 120
mkfile "$SANDBOX/disks/d2/movies/big-buck-bunny.mkv" 4096
mkfile "$SANDBOX/disks/d2/movies/sintel.mkv" 3072
mkfile "$SANDBOX/disks/d2/music/album/01-intro.flac" 600
mkfile "$SANDBOX/disks/d2/music/album/02-theme.flac" 800
mkfile "$SANDBOX/disks/d3/backups/laptop-2025-01.tar" 2048
mkfile "$SANDBOX/disks/d3/backups/laptop-2025-06.tar" 2560
mkfile "$SANDBOX/disks/d3/projects/notes.txt" 4
mkfile "$SANDBOX/disks/d3/tmp/cache.bin" 64

cat > "$SANDBOX/snapraid.conf" <<EOF
# Generated by dev/setup.sh - development sandbox, safe to modify or delete

parity $SANDBOX/parity/snapraid.parity

content $SANDBOX/parity/snapraid.content
content $SANDBOX/disks/d1/snapraid.content
content $SANDBOX/disks/d2/snapraid.content

data d1 $SANDBOX/disks/d1/
data d2 $SANDBOX/disks/d2/
data d3 $SANDBOX/disks/d3/

exclude *.content
exclude /tmp/
exclude /lost+found/

blocksize 64
autosave 10
EOF

cat > "$SANDBOX/config.json" <<'EOF'
{
  "version": "1.0.0",
  "snapraidConfigs": [
    {
      "name": "Dev Sandbox",
      "path": "snapraid.conf",
      "enabled": true
    }
  ],
  "logs": {
    "maxHistoryEntries": 50,
    "directory": "logs",
    "maxFiles": 100,
    "maxAge": 30
  }
}
EOF

echo '{ "schedules": [] }' > "$SANDBOX/schedules.json"

echo "Running initial sync..."
"$SNAPRAID" --test-skip-device -c "$SANDBOX/snapraid.conf" sync >/dev/null 2>&1 \
  || { echo "Initial sync failed" >&2; exit 1; }

# Pending changes so diff/status/sync have something to do
mkfile "$SANDBOX/disks/d1/photos/2025/new-photo.jpg" 500
mkfile "$SANDBOX/disks/d2/music/album/02-theme.flac" 820
rm "$SANDBOX/disks/d3/backups/laptop-2025-01.tar"

echo
echo "Sandbox ready. Start the app with: ./start.sh --demo"
